services:
  - type: web
    name: api
    runtime: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: servers/api/Dockerfile
    buildFilter:
      paths:
        - servers/api/**/*.ts
        - servers/api/*.json
        - servers/api/Dockerfile
    envVars:
      - fromGroup: servers/api
      - key: DATABASE_URL
        fromDatabase:
          name: saitamaDB
          property: connectionString
    domains:
      - "v1.api.saitama.fun"
databases:
  - name: saitamaDB
    user: admin
    plan: basic-256mb
